/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SseRouteImport } from './routes/sse'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SNameRouteImport } from './routes/s.$name'
import { Route as PreviewNameRouteImport } from './routes/preview.$name'
import { Route as PScreenRouteImport } from './routes/p.$screen'
import { Route as ApiLayoutRouteImport } from './routes/api.layout'

const SseRoute = SseRouteImport.update({
  id: '/sse',
  path: '/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SNameRoute = SNameRouteImport.update({
  id: '/s/$name',
  path: '/s/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewNameRoute = PreviewNameRouteImport.update({
  id: '/preview/$name',
  path: '/preview/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PScreenRoute = PScreenRouteImport.update({
  id: '/p/$screen',
  path: '/p/$screen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLayoutRoute = ApiLayoutRouteImport.update({
  id: '/api/layout',
  path: '/api/layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/design': typeof DesignRoute
  '/help': typeof HelpRoute
  '/layout': typeof LayoutRoute
  '/mcp': typeof McpRoute
  '/sse': typeof SseRoute
  '/api/layout': typeof ApiLayoutRoute
  '/p/$screen': typeof PScreenRoute
  '/preview/$name': typeof PreviewNameRoute
  '/s/$name': typeof SNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/design': typeof DesignRoute
  '/help': typeof HelpRoute
  '/layout': typeof LayoutRoute
  '/mcp': typeof McpRoute
  '/sse': typeof SseRoute
  '/api/layout': typeof ApiLayoutRoute
  '/p/$screen': typeof PScreenRoute
  '/preview/$name': typeof PreviewNameRoute
  '/s/$name': typeof SNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/design': typeof DesignRoute
  '/help': typeof HelpRoute
  '/layout': typeof LayoutRoute
  '/mcp': typeof McpRoute
  '/sse': typeof SseRoute
  '/api/layout': typeof ApiLayoutRoute
  '/p/$screen': typeof PScreenRoute
  '/preview/$name': typeof PreviewNameRoute
  '/s/$name': typeof SNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/design'
    | '/help'
    | '/layout'
    | '/mcp'
    | '/sse'
    | '/api/layout'
    | '/p/$screen'
    | '/preview/$name'
    | '/s/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/design'
    | '/help'
    | '/layout'
    | '/mcp'
    | '/sse'
    | '/api/layout'
    | '/p/$screen'
    | '/preview/$name'
    | '/s/$name'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/design'
    | '/help'
    | '/layout'
    | '/mcp'
    | '/sse'
    | '/api/layout'
    | '/p/$screen'
    | '/preview/$name'
    | '/s/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  DesignRoute: typeof DesignRoute
  HelpRoute: typeof HelpRoute
  LayoutRoute: typeof LayoutRoute
  McpRoute: typeof McpRoute
  SseRoute: typeof SseRoute
  ApiLayoutRoute: typeof ApiLayoutRoute
  PScreenRoute: typeof PScreenRoute
  PreviewNameRoute: typeof PreviewNameRoute
  SNameRoute: typeof SNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sse': {
      id: '/sse'
      path: '/sse'
      fullPath: '/sse'
      preLoaderRoute: typeof SseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$name': {
      id: '/s/$name'
      path: '/s/$name'
      fullPath: '/s/$name'
      preLoaderRoute: typeof SNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$name': {
      id: '/preview/$name'
      path: '/preview/$name'
      fullPath: '/preview/$name'
      preLoaderRoute: typeof PreviewNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$screen': {
      id: '/p/$screen'
      path: '/p/$screen'
      fullPath: '/p/$screen'
      preLoaderRoute: typeof PScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/layout': {
      id: '/api/layout'
      path: '/api/layout'
      fullPath: '/api/layout'
      preLoaderRoute: typeof ApiLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  DesignRoute: DesignRoute,
  HelpRoute: HelpRoute,
  LayoutRoute: LayoutRoute,
  McpRoute: McpRoute,
  SseRoute: SseRoute,
  ApiLayoutRoute: ApiLayoutRoute,
  PScreenRoute: PScreenRoute,
  PreviewNameRoute: PreviewNameRoute,
  SNameRoute: SNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
