/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SNameRouteImport } from './routes/s.$name'
import { Route as PreviewNameRouteImport } from './routes/preview.$name'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SNameRoute = SNameRouteImport.update({
  id: '/s/$name',
  path: '/s/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewNameRoute = PreviewNameRouteImport.update({
  id: '/preview/$name',
  path: '/preview/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/design': typeof DesignRoute
  '/mcp': typeof McpRoute
  '/preview/$name': typeof PreviewNameRoute
  '/s/$name': typeof SNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/design': typeof DesignRoute
  '/mcp': typeof McpRoute
  '/preview/$name': typeof PreviewNameRoute
  '/s/$name': typeof SNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/design': typeof DesignRoute
  '/mcp': typeof McpRoute
  '/preview/$name': typeof PreviewNameRoute
  '/s/$name': typeof SNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/design'
    | '/mcp'
    | '/preview/$name'
    | '/s/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components' | '/design' | '/mcp' | '/preview/$name' | '/s/$name'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/design'
    | '/mcp'
    | '/preview/$name'
    | '/s/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  DesignRoute: typeof DesignRoute
  McpRoute: typeof McpRoute
  PreviewNameRoute: typeof PreviewNameRoute
  SNameRoute: typeof SNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$name': {
      id: '/s/$name'
      path: '/s/$name'
      fullPath: '/s/$name'
      preLoaderRoute: typeof SNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$name': {
      id: '/preview/$name'
      path: '/preview/$name'
      fullPath: '/preview/$name'
      preLoaderRoute: typeof PreviewNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  DesignRoute: DesignRoute,
  McpRoute: McpRoute,
  PreviewNameRoute: PreviewNameRoute,
  SNameRoute: SNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
